# Generated by Django 3.2.9 on 2022-03-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=12)),
                ('start_time', models.CharField(max_length=20)),
                ('finish_time', models.CharField(max_length=20)),
                ('time_minute', models.CharField(max_length=10)),
            ],
        ),
    ]
